//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from TableWithSchemaSpecificationWithCustomSelectList.g4 by ANTLR 4.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace dbsc.Core.Antlr {
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using System.Collections.Generic;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.3")]
[System.CLSCompliant(false)]
public partial class TableWithSchemaSpecificationWithCustomSelectListParser : Parser {
	public const int
		T__0=1, MS_UNENCLOSED_ID_NAME=2, MS_BRACKET_ENCLOSED_ID=3, PG_UNENCLOSED_ID_NAME=4, 
		PG_QUOTE_ENCLOSED_ID=5, WS_NO_NEWLINE=6, NEWLINE=7, LETTER=8, NUMBER=9, 
		WILDCARD=10, NEGATER=11, CUSTOM_SELECT=12;
	public static readonly string[] tokenNames = {
		"<INVALID>", "'.'", "MS_UNENCLOSED_ID_NAME", "MS_BRACKET_ENCLOSED_ID", 
		"PG_UNENCLOSED_ID_NAME", "PG_QUOTE_ENCLOSED_ID", "WS_NO_NEWLINE", "NEWLINE", 
		"LETTER", "NUMBER", "'*'", "'-'", "CUSTOM_SELECT"
	};
	public const int
		RULE_tableSpecificationList = 0, RULE_tableSpecificationLine = 1, RULE_possiblyQualifiedTableLine = 2, 
		RULE_possiblyQualifiedTable = 3, RULE_unqualifiedTable = 4, RULE_qualifiedTable = 5, 
		RULE_identifier = 6;
	public static readonly string[] ruleNames = {
		"tableSpecificationList", "tableSpecificationLine", "possiblyQualifiedTableLine", 
		"possiblyQualifiedTable", "unqualifiedTable", "qualifiedTable", "identifier"
	};

	public override string GrammarFileName { get { return "TableWithSchemaSpecificationWithCustomSelectList.g4"; } }

	public override string[] TokenNames { get { return tokenNames; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }


		private IdentifierSyntax _flavor = IdentifierSyntax.SqlServer;
		public IdentifierSyntax Flavor { get { return _flavor; } set { _flavor = value; } }

		public TableWithSchemaSpecificationWithCustomSelectListParser(ITokenStream input, IdentifierSyntax flavor)
			: this (input)
		{
			Flavor = flavor;
		}

	public TableWithSchemaSpecificationWithCustomSelectListParser(ITokenStream input)
		: base(input)
	{
		_interp = new ParserATNSimulator(this,_ATN);
	}
	public partial class TableSpecificationListContext : ParserRuleContext {
		public ITerminalNode[] NEWLINE() { return GetTokens(TableWithSchemaSpecificationWithCustomSelectListParser.NEWLINE); }
		public ITerminalNode Eof() { return GetToken(TableWithSchemaSpecificationWithCustomSelectListParser.Eof, 0); }
		public ITerminalNode NEWLINE(int i) {
			return GetToken(TableWithSchemaSpecificationWithCustomSelectListParser.NEWLINE, i);
		}
		public TableSpecificationLineContext[] tableSpecificationLine() {
			return GetRuleContexts<TableSpecificationLineContext>();
		}
		public TableSpecificationLineContext tableSpecificationLine(int i) {
			return GetRuleContext<TableSpecificationLineContext>(i);
		}
		public TableSpecificationListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_tableSpecificationList; } }
	}

	[RuleVersion(0)]
	public TableSpecificationListContext tableSpecificationList() {
		TableSpecificationListContext _localctx = new TableSpecificationListContext(_ctx, State);
		EnterRule(_localctx, 0, RULE_tableSpecificationList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 14; tableSpecificationLine();
			State = 19;
			_errHandler.Sync(this);
			_la = _input.La(1);
			while (_la==NEWLINE) {
				{
				{
				State = 15; Match(NEWLINE);
				State = 16; tableSpecificationLine();
				}
				}
				State = 21;
				_errHandler.Sync(this);
				_la = _input.La(1);
			}
			State = 22; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TableSpecificationLineContext : ParserRuleContext {
		public PossiblyQualifiedTableLineContext possiblyQualifiedTableLine() {
			return GetRuleContext<PossiblyQualifiedTableLineContext>(0);
		}
		public TableSpecificationLineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_tableSpecificationLine; } }
	}

	[RuleVersion(0)]
	public TableSpecificationLineContext tableSpecificationLine() {
		TableSpecificationLineContext _localctx = new TableSpecificationLineContext(_ctx, State);
		EnterRule(_localctx, 2, RULE_tableSpecificationLine);
		try {
			State = 26;
			switch ( Interpreter.AdaptivePredict(_input,1,_ctx) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 24; possiblyQualifiedTableLine();
				}
				break;

			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PossiblyQualifiedTableLineContext : ParserRuleContext {
		public ITerminalNode CUSTOM_SELECT() { return GetToken(TableWithSchemaSpecificationWithCustomSelectListParser.CUSTOM_SELECT, 0); }
		public ITerminalNode NEGATER() { return GetToken(TableWithSchemaSpecificationWithCustomSelectListParser.NEGATER, 0); }
		public PossiblyQualifiedTableContext possiblyQualifiedTable() {
			return GetRuleContext<PossiblyQualifiedTableContext>(0);
		}
		public PossiblyQualifiedTableLineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_possiblyQualifiedTableLine; } }
	}

	[RuleVersion(0)]
	public PossiblyQualifiedTableLineContext possiblyQualifiedTableLine() {
		PossiblyQualifiedTableLineContext _localctx = new PossiblyQualifiedTableLineContext(_ctx, State);
		EnterRule(_localctx, 4, RULE_possiblyQualifiedTableLine);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 29;
			switch ( Interpreter.AdaptivePredict(_input,2,_ctx) ) {
			case 1:
				{
				State = 28; Match(NEGATER);
				}
				break;
			}
			State = 31; possiblyQualifiedTable();
			State = 33;
			_la = _input.La(1);
			if (_la==CUSTOM_SELECT) {
				{
				State = 32; Match(CUSTOM_SELECT);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PossiblyQualifiedTableContext : ParserRuleContext {
		public UnqualifiedTableContext unqualifiedTable() {
			return GetRuleContext<UnqualifiedTableContext>(0);
		}
		public QualifiedTableContext qualifiedTable() {
			return GetRuleContext<QualifiedTableContext>(0);
		}
		public PossiblyQualifiedTableContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_possiblyQualifiedTable; } }
	}

	[RuleVersion(0)]
	public PossiblyQualifiedTableContext possiblyQualifiedTable() {
		PossiblyQualifiedTableContext _localctx = new PossiblyQualifiedTableContext(_ctx, State);
		EnterRule(_localctx, 6, RULE_possiblyQualifiedTable);
		try {
			State = 37;
			switch ( Interpreter.AdaptivePredict(_input,4,_ctx) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 35; unqualifiedTable();
				}
				break;

			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 36; qualifiedTable();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UnqualifiedTableContext : ParserRuleContext {
		public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public UnqualifiedTableContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_unqualifiedTable; } }
	}

	[RuleVersion(0)]
	public UnqualifiedTableContext unqualifiedTable() {
		UnqualifiedTableContext _localctx = new UnqualifiedTableContext(_ctx, State);
		EnterRule(_localctx, 8, RULE_unqualifiedTable);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 39; identifier();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class QualifiedTableContext : ParserRuleContext {
		public IdentifierContext schema;
		public IdentifierContext table;
		public IdentifierContext identifier(int i) {
			return GetRuleContext<IdentifierContext>(i);
		}
		public IdentifierContext[] identifier() {
			return GetRuleContexts<IdentifierContext>();
		}
		public QualifiedTableContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_qualifiedTable; } }
	}

	[RuleVersion(0)]
	public QualifiedTableContext qualifiedTable() {
		QualifiedTableContext _localctx = new QualifiedTableContext(_ctx, State);
		EnterRule(_localctx, 10, RULE_qualifiedTable);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 41; _localctx.schema = identifier();
			State = 42; Match(T__0);
			State = 43; _localctx.table = identifier();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdentifierContext : ParserRuleContext {
		public ITerminalNode MS_UNENCLOSED_ID_NAME() { return GetToken(TableWithSchemaSpecificationWithCustomSelectListParser.MS_UNENCLOSED_ID_NAME, 0); }
		public ITerminalNode PG_QUOTE_ENCLOSED_ID() { return GetToken(TableWithSchemaSpecificationWithCustomSelectListParser.PG_QUOTE_ENCLOSED_ID, 0); }
		public ITerminalNode PG_UNENCLOSED_ID_NAME() { return GetToken(TableWithSchemaSpecificationWithCustomSelectListParser.PG_UNENCLOSED_ID_NAME, 0); }
		public ITerminalNode MS_BRACKET_ENCLOSED_ID() { return GetToken(TableWithSchemaSpecificationWithCustomSelectListParser.MS_BRACKET_ENCLOSED_ID, 0); }
		public IdentifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_identifier; } }
	}

	[RuleVersion(0)]
	public IdentifierContext identifier() {
		IdentifierContext _localctx = new IdentifierContext(_ctx, State);
		EnterRule(_localctx, 12, RULE_identifier);
		try {
			State = 53;
			switch ( Interpreter.AdaptivePredict(_input,5,_ctx) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 45;
				if (!(Flavor == IdentifierSyntax.SqlServer)) throw new FailedPredicateException(this, "Flavor == IdentifierSyntax.SqlServer");
				State = 46; Match(MS_UNENCLOSED_ID_NAME);
				}
				break;

			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 47;
				if (!(Flavor == IdentifierSyntax.SqlServer)) throw new FailedPredicateException(this, "Flavor == IdentifierSyntax.SqlServer");
				State = 48; Match(MS_BRACKET_ENCLOSED_ID);
				}
				break;

			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 49;
				if (!(Flavor == IdentifierSyntax.Postgres)) throw new FailedPredicateException(this, "Flavor == IdentifierSyntax.Postgres");
				State = 50; Match(PG_UNENCLOSED_ID_NAME);
				}
				break;

			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 51;
				if (!(Flavor == IdentifierSyntax.Postgres)) throw new FailedPredicateException(this, "Flavor == IdentifierSyntax.Postgres");
				State = 52; Match(PG_QUOTE_ENCLOSED_ID);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 6: return identifier_sempred((IdentifierContext)_localctx, predIndex);
		}
		return true;
	}
	private bool identifier_sempred(IdentifierContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Flavor == IdentifierSyntax.SqlServer;

		case 1: return Flavor == IdentifierSyntax.SqlServer;

		case 2: return Flavor == IdentifierSyntax.Postgres;

		case 3: return Flavor == IdentifierSyntax.Postgres;
		}
		return true;
	}

	public static readonly string _serializedATN =
		"\x3\xAF6F\x8320\x479D\xB75C\x4880\x1605\x191C\xAB37\x3\xE:\x4\x2\t\x2"+
		"\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x4\x6\t\x6\x4\a\t\a\x4\b\t\b\x3\x2\x3"+
		"\x2\x3\x2\a\x2\x14\n\x2\f\x2\xE\x2\x17\v\x2\x3\x2\x3\x2\x3\x3\x3\x3\x5"+
		"\x3\x1D\n\x3\x3\x4\x5\x4 \n\x4\x3\x4\x3\x4\x5\x4$\n\x4\x3\x5\x3\x5\x5"+
		"\x5(\n\x5\x3\x6\x3\x6\x3\a\x3\a\x3\a\x3\a\x3\b\x3\b\x3\b\x3\b\x3\b\x3"+
		"\b\x3\b\x3\b\x5\b\x38\n\b\x3\b\x2\x2\x2\t\x2\x2\x4\x2\x6\x2\b\x2\n\x2"+
		"\f\x2\xE\x2\x2\x2:\x2\x10\x3\x2\x2\x2\x4\x1C\x3\x2\x2\x2\x6\x1F\x3\x2"+
		"\x2\x2\b\'\x3\x2\x2\x2\n)\x3\x2\x2\x2\f+\x3\x2\x2\x2\xE\x37\x3\x2\x2\x2"+
		"\x10\x15\x5\x4\x3\x2\x11\x12\a\t\x2\x2\x12\x14\x5\x4\x3\x2\x13\x11\x3"+
		"\x2\x2\x2\x14\x17\x3\x2\x2\x2\x15\x13\x3\x2\x2\x2\x15\x16\x3\x2\x2\x2"+
		"\x16\x18\x3\x2\x2\x2\x17\x15\x3\x2\x2\x2\x18\x19\a\x2\x2\x3\x19\x3\x3"+
		"\x2\x2\x2\x1A\x1D\x5\x6\x4\x2\x1B\x1D\x3\x2\x2\x2\x1C\x1A\x3\x2\x2\x2"+
		"\x1C\x1B\x3\x2\x2\x2\x1D\x5\x3\x2\x2\x2\x1E \a\r\x2\x2\x1F\x1E\x3\x2\x2"+
		"\x2\x1F \x3\x2\x2\x2 !\x3\x2\x2\x2!#\x5\b\x5\x2\"$\a\xE\x2\x2#\"\x3\x2"+
		"\x2\x2#$\x3\x2\x2\x2$\a\x3\x2\x2\x2%(\x5\n\x6\x2&(\x5\f\a\x2\'%\x3\x2"+
		"\x2\x2\'&\x3\x2\x2\x2(\t\x3\x2\x2\x2)*\x5\xE\b\x2*\v\x3\x2\x2\x2+,\x5"+
		"\xE\b\x2,-\a\x3\x2\x2-.\x5\xE\b\x2.\r\x3\x2\x2\x2/\x30\x6\b\x2\x2\x30"+
		"\x38\a\x4\x2\x2\x31\x32\x6\b\x3\x2\x32\x38\a\x5\x2\x2\x33\x34\x6\b\x4"+
		"\x2\x34\x38\a\x6\x2\x2\x35\x36\x6\b\x5\x2\x36\x38\a\a\x2\x2\x37/\x3\x2"+
		"\x2\x2\x37\x31\x3\x2\x2\x2\x37\x33\x3\x2\x2\x2\x37\x35\x3\x2\x2\x2\x38"+
		"\xF\x3\x2\x2\x2\b\x15\x1C\x1F#\'\x37";
	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());
}
} // namespace dbsc.Core.Antlr
